# Generated by Django 3.2.5 on 2021-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
