# Generated by Django 3.2.5 on 2021-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_orders_order_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'get_latest_by': ['id'], 'ordering': ['-id'], 'verbose_name_plural': 'orders'},
        ),
        migrations.AddField(
            model_name='order_line',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
